"""
Convert a TFLite flatbuffer to a C header for ESP32 firmware.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def _default_tflite_path() -> Path:
    preferred = Path("tflite_actors/model_int8.tflite")
    fallback = Path("tflite_actors/model_fp32.tflite")
    return preferred if preferred.exists() else fallback


def _looks_like_tflite(data: bytes) -> bool:
    return len(data) >= 8 and data[4:8] == b"TFL3"


def hex_to_c_array(hex_data: bytes, var_name: str) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by deployment/convert_tflite_to_c.py",
        f"const unsigned int {var_name}_len = {len(hex_data)};",
        f"const unsigned char {var_name}[] __attribute__((aligned(16))) = {{",
    ]

    row = []
    for index, value in enumerate(hex_data, start=1):
        row.append(format(value, "#04x") + ("," if index < len(hex_data) else ""))
        if index % 12 == 0:
            lines.append("  " + " ".join(row))
            row = []

    if row:
        lines.append("  " + " ".join(row))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def convert_tflite_to_c(
    tflite_path: str | None = None,
    output_path: str = "model.h",
    var_name: str = "dbs_model",
) -> bool:
    source_path = Path(tflite_path) if tflite_path is not None else _default_tflite_path()
    target_path = Path(output_path)

    print("=" * 70)
    print("Converting TFLite model to ESP32 header")
    print("=" * 70)

    print("\n1. Checking TFLite file...")
    if not source_path.exists():
        print(f"   [X] ERROR: TFLite file not found at {source_path}")
        return False

    data = source_path.read_bytes()
    if not _looks_like_tflite(data):
        print("   [X] ERROR: input file is not a valid TFLite flatbuffer (missing TFL3 signature)")
        return False

    print(f"   [OK] TFLite file found: {source_path}")
    print(f"   File size: {len(data)} bytes")

    print("\n2. Generating C header...")
    header = hex_to_c_array(data, var_name)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(header)
    print(f"   [OK] Header written: {target_path}")

    print("\n3. Verification...")
    written = target_path.read_text().splitlines()[:6]
    for line in written:
        print(f"   {line}")

    print("\n" + "=" * 70)
    print("C HEADER CONVERSION COMPLETE [OK]")
    print("=" * 70)
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert a TFLite model into a C header.")
    parser.add_argument("--tflite-path", default=None)
    parser.add_argument("--output-path", default="model.h")
    parser.add_argument("--var-name", default="dbs_model")
    args = parser.parse_args()

    success = convert_tflite_to_c(
        tflite_path=args.tflite_path,
        output_path=args.output_path,
        var_name=args.var_name,
    )
    raise SystemExit(0 if success else 1)
